// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: cmd/schemas/book.proto

package schemas

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Genre int32

const (
	Genre_ACTION    Genre = 0
	Genre_DRAMA     Genre = 1
	Genre_ROMANCE   Genre = 2
	Genre_THRILLER  Genre = 3
	Genre_COMEDY    Genre = 4
	Genre_FANTASY   Genre = 5
	Genre_SCIFI     Genre = 6
	Genre_HORROR    Genre = 7
	Genre_MYSTERY   Genre = 8
	Genre_TECHNICAL Genre = 9
)

// Enum value maps for Genre.
var (
	Genre_name = map[int32]string{
		0: "ACTION",
		1: "DRAMA",
		2: "ROMANCE",
		3: "THRILLER",
		4: "COMEDY",
		5: "FANTASY",
		6: "SCIFI",
		7: "HORROR",
		8: "MYSTERY",
		9: "TECHNICAL",
	}
	Genre_value = map[string]int32{
		"ACTION":    0,
		"DRAMA":     1,
		"ROMANCE":   2,
		"THRILLER":  3,
		"COMEDY":    4,
		"FANTASY":   5,
		"SCIFI":     6,
		"HORROR":    7,
		"MYSTERY":   8,
		"TECHNICAL": 9,
	}
)

func (x Genre) Enum() *Genre {
	p := new(Genre)
	*p = x
	return p
}

func (x Genre) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Genre) Descriptor() protoreflect.EnumDescriptor {
	return file_cmd_schemas_book_proto_enumTypes[0].Descriptor()
}

func (Genre) Type() protoreflect.EnumType {
	return &file_cmd_schemas_book_proto_enumTypes[0]
}

func (x Genre) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Genre.Descriptor instead.
func (Genre) EnumDescriptor() ([]byte, []int) {
	return file_cmd_schemas_book_proto_rawDescGZIP(), []int{0}
}

type Book struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Authors       []*Author              `protobuf:"bytes,3,rep,name=authors,proto3" json:"authors,omitempty"`
	Publisher     *Publisher             `protobuf:"bytes,4,opt,name=publisher,proto3" json:"publisher,omitempty"`
	Genre         Genre                  `protobuf:"varint,5,opt,name=genre,proto3,enum=schema.Genre" json:"genre,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Book) Reset() {
	*x = Book{}
	mi := &file_cmd_schemas_book_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Book) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Book) ProtoMessage() {}

func (x *Book) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_schemas_book_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Book.ProtoReflect.Descriptor instead.
func (*Book) Descriptor() ([]byte, []int) {
	return file_cmd_schemas_book_proto_rawDescGZIP(), []int{0}
}

func (x *Book) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Book) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Book) GetAuthors() []*Author {
	if x != nil {
		return x.Authors
	}
	return nil
}

func (x *Book) GetPublisher() *Publisher {
	if x != nil {
		return x.Publisher
	}
	return nil
}

func (x *Book) GetGenre() Genre {
	if x != nil {
		return x.Genre
	}
	return Genre_ACTION
}

type Books struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Books         []*Book                `protobuf:"bytes,1,rep,name=books,proto3" json:"books,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Books) Reset() {
	*x = Books{}
	mi := &file_cmd_schemas_book_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Books) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Books) ProtoMessage() {}

func (x *Books) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_schemas_book_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Books.ProtoReflect.Descriptor instead.
func (*Books) Descriptor() ([]byte, []int) {
	return file_cmd_schemas_book_proto_rawDescGZIP(), []int{1}
}

func (x *Books) GetBooks() []*Book {
	if x != nil {
		return x.Books
	}
	return nil
}

type Author struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Author) Reset() {
	*x = Author{}
	mi := &file_cmd_schemas_book_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Author) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Author) ProtoMessage() {}

func (x *Author) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_schemas_book_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Author.ProtoReflect.Descriptor instead.
func (*Author) Descriptor() ([]byte, []int) {
	return file_cmd_schemas_book_proto_rawDescGZIP(), []int{2}
}

func (x *Author) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Author) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Authors struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authors       []*Author              `protobuf:"bytes,1,rep,name=authors,proto3" json:"authors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Authors) Reset() {
	*x = Authors{}
	mi := &file_cmd_schemas_book_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Authors) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Authors) ProtoMessage() {}

func (x *Authors) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_schemas_book_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Authors.ProtoReflect.Descriptor instead.
func (*Authors) Descriptor() ([]byte, []int) {
	return file_cmd_schemas_book_proto_rawDescGZIP(), []int{3}
}

func (x *Authors) GetAuthors() []*Author {
	if x != nil {
		return x.Authors
	}
	return nil
}

type Publisher struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Publisher) Reset() {
	*x = Publisher{}
	mi := &file_cmd_schemas_book_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Publisher) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Publisher) ProtoMessage() {}

func (x *Publisher) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_schemas_book_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Publisher.ProtoReflect.Descriptor instead.
func (*Publisher) Descriptor() ([]byte, []int) {
	return file_cmd_schemas_book_proto_rawDescGZIP(), []int{4}
}

func (x *Publisher) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Publisher) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_cmd_schemas_book_proto protoreflect.FileDescriptor

const file_cmd_schemas_book_proto_rawDesc = "" +
	"\n" +
	"\x16cmd/schemas/book.proto\x12\x06schema\"\xac\x01\n" +
	"\x04Book\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12(\n" +
	"\aauthors\x18\x03 \x03(\v2\x0e.schema.AuthorR\aauthors\x12/\n" +
	"\tpublisher\x18\x04 \x01(\v2\x11.schema.PublisherR\tpublisher\x12#\n" +
	"\x05genre\x18\x05 \x01(\x0e2\r.schema.GenreR\x05genre\"+\n" +
	"\x05Books\x12\"\n" +
	"\x05books\x18\x01 \x03(\v2\f.schema.BookR\x05books\",\n" +
	"\x06Author\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"3\n" +
	"\aAuthors\x12(\n" +
	"\aauthors\x18\x01 \x03(\v2\x0e.schema.AuthorR\aauthors\"/\n" +
	"\tPublisher\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name*\x85\x01\n" +
	"\x05Genre\x12\n" +
	"\n" +
	"\x06ACTION\x10\x00\x12\t\n" +
	"\x05DRAMA\x10\x01\x12\v\n" +
	"\aROMANCE\x10\x02\x12\f\n" +
	"\bTHRILLER\x10\x03\x12\n" +
	"\n" +
	"\x06COMEDY\x10\x04\x12\v\n" +
	"\aFANTASY\x10\x05\x12\t\n" +
	"\x05SCIFI\x10\x06\x12\n" +
	"\n" +
	"\x06HORROR\x10\a\x12\v\n" +
	"\aMYSTERY\x10\b\x12\r\n" +
	"\tTECHNICAL\x10\tB.Z,github.com/alcb1310/proto-server/cmd/schemasb\x06proto3"

var (
	file_cmd_schemas_book_proto_rawDescOnce sync.Once
	file_cmd_schemas_book_proto_rawDescData []byte
)

func file_cmd_schemas_book_proto_rawDescGZIP() []byte {
	file_cmd_schemas_book_proto_rawDescOnce.Do(func() {
		file_cmd_schemas_book_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cmd_schemas_book_proto_rawDesc), len(file_cmd_schemas_book_proto_rawDesc)))
	})
	return file_cmd_schemas_book_proto_rawDescData
}

var file_cmd_schemas_book_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cmd_schemas_book_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_cmd_schemas_book_proto_goTypes = []any{
	(Genre)(0),        // 0: schema.Genre
	(*Book)(nil),      // 1: schema.Book
	(*Books)(nil),     // 2: schema.Books
	(*Author)(nil),    // 3: schema.Author
	(*Authors)(nil),   // 4: schema.Authors
	(*Publisher)(nil), // 5: schema.Publisher
}
var file_cmd_schemas_book_proto_depIdxs = []int32{
	3, // 0: schema.Book.authors:type_name -> schema.Author
	5, // 1: schema.Book.publisher:type_name -> schema.Publisher
	0, // 2: schema.Book.genre:type_name -> schema.Genre
	1, // 3: schema.Books.books:type_name -> schema.Book
	3, // 4: schema.Authors.authors:type_name -> schema.Author
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_cmd_schemas_book_proto_init() }
func file_cmd_schemas_book_proto_init() {
	if File_cmd_schemas_book_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cmd_schemas_book_proto_rawDesc), len(file_cmd_schemas_book_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cmd_schemas_book_proto_goTypes,
		DependencyIndexes: file_cmd_schemas_book_proto_depIdxs,
		EnumInfos:         file_cmd_schemas_book_proto_enumTypes,
		MessageInfos:      file_cmd_schemas_book_proto_msgTypes,
	}.Build()
	File_cmd_schemas_book_proto = out.File
	file_cmd_schemas_book_proto_goTypes = nil
	file_cmd_schemas_book_proto_depIdxs = nil
}
